name: test_apps
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.4.0
  dio: ^5.6.0
  flutter_spinkit: ^5.2.1
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.6
  intl: ^0.19.0
  get_it: ^7.7.0
  internet_connection_checker_plus: ^2.5.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  package_info_plus: ^8.0.1
  stream_transform: ^2.1.0
  dartz: ^0.10.1
  hive: ^2.2.3
  flutter_easyloading: ^3.0.5
  http: ^1.2.2
  azure_application_insights: ^4.0.1
  flutter_bloc: ^8.1.6
  shimmer: ^3.0.0
  formz: ^0.7.0
  flutter_toggle_tab: ^1.4.1
  gap: ^3.0.1
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
